# Generated by Django 2.2.4 on 2020-03-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_restrict_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='vip_verify_account',
            field=models.BooleanField(default=False),
        ),
    ]
