# Generated by Django 2.2.4 on 2020-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200321_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_account',
            field=models.BooleanField(default=True),
        ),
    ]
