# Generated by Django 2.2.4 on 2020-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200322_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coverpic',
        ),
        migrations.AddField(
            model_name='profile',
            name='Accepting_Contributions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Cover_Video',
            field=models.FileField(default='default.mp4', upload_to='cover_videos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Digital_Bank_Name_With_Account_Number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='Location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='QR_Snap',
            field=models.ImageField(default='default.jpg', upload_to='QR_Snap'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default=False),
        ),
    ]
