# Generated by Django 2.2.4 on 2020-05-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_messenger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Deactivate_Contributions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Disable_Messenger_ID',
            field=models.BooleanField(default=False),
        ),
    ]
