# Generated by Django 2.2.4 on 2021-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200519_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Relationship_status',
            field=models.CharField(choices=[('M', 'Single'), ('F', 'Married')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='UPI_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gif',
            field=models.ImageField(default=False, upload_to='profile_gif'),
        ),
    ]
