# Generated by Django 2.2.4 on 2021-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210409_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'FeMale'), ('Custom', 'Custom')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Relationship_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='', max_length=7),
        ),
    ]
