# Generated by Django 2.2.4 on 2021-05-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210416_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Page_activation',
            field=models.BooleanField(default=False),
        ),
    ]
