# Generated by Django 2.2.4 on 2021-05-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_page_activation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
