# Generated by Django 2.2.4 on 2020-01-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments-pics'),
        ),
        migrations.AddField(
            model_name='comment',
            name='voice_record',
            field=models.FileField(blank=True, null=True, upload_to='voice-comments'),
        ),
    ]
