# Generated by Django 2.2.4 on 2020-02-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
