# Generated by Django 2.2.4 on 2020-03-14 19:32

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200215_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos', validators=[blog.validators.validate_file_extension]),
        ),
    ]
