# Generated by Django 2.2.4 on 2020-03-17 15:28

import blog.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_auto_20200314_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='post_audios', validators=[blog.validators.validate_audiofile_extension]),
        ),
        migrations.AddField(
            model_name='post',
            name='restrict_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
