# Generated by Django 2.2.4 on 2020-03-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='massage',
            field=models.TextField(),
        ),
    ]
