# Generated by Django 2.2.4 on 2020-03-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200320_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
