# Generated by Django 2.2.4 on 2021-03-26 07:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0022_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='coder',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='react',
            field=models.ManyToManyField(blank=True, related_name='react', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='coder',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='haha',
            field=models.ManyToManyField(blank=True, related_name='haha', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='restrict_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='sad',
            field=models.ManyToManyField(blank=True, related_name='sad', to=settings.AUTH_USER_MODEL),
        ),
    ]
