# Generated by Django 2.2.4 on 2021-04-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210401_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_artist_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_poster',
            field=models.ImageField(blank=True, null=True, upload_to='audip_poster_pics'),
        ),
    ]
