# Generated by Django 2.2.4 on 2021-05-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210425_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='restrict_share',
            new_name='restrict_repost',
        ),
        migrations.AlterField(
            model_name='post',
            name='audio_poster',
            field=models.ImageField(default='posterdefault.jpg', upload_to='audip_poster_pics'),
        ),
    ]
