# Generated by Django 2.2.4 on 2021-05-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210512_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio_poster',
            field=models.ImageField(blank=True, null=True, upload_to='audip_poster_pics'),
        ),
    ]
